name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest

    - name: Executar testes
      run: |
        pytest  # ou substitua pelo seu comando real

    - name: Deploy no PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        pip install --user pythonanywhere
        python -m pythonanywhere.deploy \
          --username $PA_USERNAME \
          --api_token $PA_API_TOKEN \
          --site vrunski.pythonanywhere.com \
          --path /home/vrunski/Strong-Password-A3
